name: Pull Request Tests

on: [pull_request]

jobs:
  #########
  # Tests #
  #########
  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        alpine:
          - 3.16
          - 3.17
          - 3.18
          - 3.19
          - 3.20
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install snmp
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update -y
          sudo apt-get install snmp -y

      - name: Running Tests
        env:
          ALPINE_VERSION: ${{ matrix.alpine }}
        run: ./test.sh
